const fs = require('fs').promises;
const path = require('path');

/**
 * Precise DXF Exporter for AutoCAD Compatibility
 * Creates industry-standard DXF files with precise dimensions and layers
 */
class PreciseDxfExporter {
  constructor() {
    this.dxfVersion = 'AC1015'; // AutoCAD 2000 format for maximum compatibility
    this.precision = 4; // Decimal places for coordinates
  }

  /**
   * Export layout to precise DXF format
   */
  async exportToDXF(layout, filename, options = {}) {
    try {
      const dxfContent = this.generateDXFContent(layout, options);
      const filePath = path.join(process.cwd(), 'exports', `${filename}.dxf`);
      
      await fs.mkdir(path.dirname(filePath), { recursive: true });
      await fs.writeFile(filePath, dxfContent, 'utf8');
      
      return {
        success: true,
        filePath: filePath,
        filename: `${filename}.dxf`,
        size: Buffer.byteLength(dxfContent, 'utf8'),
        layers: this.getLayerInfo(layout)
      };

    } catch (error) {
      console.error('DXF export error:', error);
      throw new Error('Failed to export DXF file: ' + error.message);
    }
  }

  /**
   * Generate DXF file content
   */
  generateDXFContent(layout, options) {
    const sections = [
      this.generateHeaderSection(layout, options),
      this.generateClassesSection(),
      this.generateTablesSection(layout, options),
      this.generateBlocksSection(layout, options),
      this.generateEntitiesSection(layout, options),
      this.generateObjectsSection(layout, options)
    ];

    return sections.join('\n');
  }

  /**
   * Generate DXF header section
   */
  generateHeaderSection(layout, options) {
    const header = [
      '0',
      'SECTION',
      '2',
      'HEADER',
      '9',
      '$ACADVER',
      '1',
      this.dxfVersion,
      '9',
      '$INSBASE',
      '10',
      '0.0',
      '20',
      '0.0',
      '30',
      '0.0',
      '9',
      '$EXTMIN',
      '10',
      '0.0',
      '20',
      '0.0',
      '30',
      '0.0',
      '9',
      '$EXTMAX',
      '10',
      layout.plot.width.toFixed(this.precision),
      '20',
      layout.plot.length.toFixed(this.precision),
      '30',
      '0.0',
      '9',
      '$LIMMIN',
      '10',
      '0.0',
      '20',
      '0.0',
      '9',
      '$LIMMAX',
      '10',
      layout.plot.width.toFixed(this.precision),
      '20',
      layout.plot.length.toFixed(this.precision),
      '9',
      '$DIMSCALE',
      '40',
      '1.0',
      '9',
      '$DIMASZ',
      '40',
      '2.5',
      '9',
      '$DIMEXO',
      '40',
      '0.625',
      '9',
      '$DIMDLI',
      '40',
      '3.75',
      '9',
      '$DIMEXE',
      '40',
      '1.25',
      '9',
      '$DIMCEN',
      '40',
      '1.0',
      '9',
      '$DIMTSZ',
      '40',
      '0.0',
      '9',
      '$DIMTOL',
      '70',
      '0',
      '9',
      '$DIMLIM',
      '70',
      '0',
      '9',
      '$DIMTIH',
      '70',
      '0',
      '9',
      '$DIMTOH',
      '70',
      '0',
      '9',
      '$DIMSE1',
      '70',
      '0',
      '9',
      '$DIMSE2',
      '70',
      '0',
      '9',
      '$DIMTAD',
      '70',
      '1',
      '9',
      '$DIMZIN',
      '70',
      '0',
      '9',
      '$DIMAZIN',
      '70',
      '0',
      '9',
      '$DIMTXT',
      '40',
      '2.5',
      '9',
      '$DIMCML',
      '70',
      '0',
      '9',
      '$DIMCLRT',
      '70',
      '7',
      '9',
      '$DIMCLRE',
      '70',
      '7',
      '9',
      '$DIMCLRD',
      '70',
      '7',
      '9',
      '$DIMLFAC',
      '40',
      '1.0',
      '9',
      '$DIMTOFL',
      '70',
      '1',
      '9',
      '$DIMTVP',
      '40',
      '0.0',
      '9',
      '$DIMGAP',
      '40',
      '0.625',
      '0',
      'ENDSEC'
    ];

    return header.join('\n');
  }

  /**
   * Generate DXF classes section
   */
  generateClassesSection() {
    const classes = [
      '0',
      'SECTION',
      '2',
      'CLASSES',
      '0',
      'CLASS',
      '1',
      'ACDBDICTIONARYWDFLT',
      '2',
      'AcDbDictionaryWithDefault',
      '3',
      'AcDbDictionaryWithDefault|Product Desc:     AcDbDictionaryWithDefault 2.0  |',
      '90',
      '0',
      '91',
      '1',
      '280',
      '0',
      '281',
      '0',
      '0',
      'CLASS',
      '1',
      'DICTIONARYVAR',
      '2',
      'AcDbDictionaryVar',
      '3',
      'AcDbDictionaryVar|Product Desc:     AcDbDictionaryVar 1.0  |',
      '90',
      '0',
      '91',
      '1',
      '280',
      '0',
      '281',
      '0',
      '0',
      'ENDSEC'
    ];

    return classes.join('\n');
  }

  /**
   * Generate DXF tables section
   */
  generateTablesSection(layout, options) {
    const tables = [
      '0',
      'SECTION',
      '2',
      'TABLES',
      // VPORT table
      '0',
      'TABLE',
      '2',
      'VPORT',
      '70',
      '1',
      '0',
      'VPORT',
      '2',
      '*Active',
      '70',
      '0',
      '10',
      '0.0',
      '20',
      '0.0',
      '11',
      '1.0',
      '21',
      '1.0',
      '12',
      '0.0',
      '22',
      '0.0',
      '13',
      '0.0',
      '23',
      '0.0',
      '14',
      '10.0',
      '24',
      '10.0',
      '15',
      '10.0',
      '25',
      '10.0',
      '16',
      '0.0',
      '26',
      '0.0',
      '36',
      '1.0',
      '17',
      '0.0',
      '27',
      '0.0',
      '37',
      '0.0',
      '40',
      '10.0',
      '41',
      '1.0',
      '42',
      '50.0',
      '43',
      '0.0',
      '44',
      '0.0',
      '50',
      '0.0',
      '51',
      '0.0',
      '71',
      '0',
      '72',
      '100',
      '73',
      '1',
      '74',
      '3',
      '75',
      '0',
      '76',
      '0',
      '77',
      '0',
      '78',
      '0',
      '0',
      'ENDTAB',
      // LTYPE table
      '0',
      'TABLE',
      '2',
      'LTYPE',
      '70',
      '6',
      '0',
      'LTYPE',
      '2',
      'CONTINUOUS',
      '70',
      '64',
      '3',
      'Solid line',
      '72',
      '65',
      '73',
      '0',
      '40',
      '0.0',
      '0',
      'LTYPE',
      '2',
      'HIDDEN',
      '70',
      '64',
      '3',
      'Hidden . . . . .',
      '72',
      '65',
      '73',
      '2',
      '40',
      '10.0',
      '49',
      '5.0',
      '49',
      '-5.0',
      '0',
      'LTYPE',
      '2',
      'CENTER',
      '70',
      '64',
      '3',
      'Center ____ . . ____ . . ____ . . ____ . . ____',
      '72',
      '65',
      '73',
      '4',
      '40',
      '40.0',
      '49',
      '20.0',
      '49',
      '-2.0',
      '49',
      '2.0',
      '49',
      '-2.0',
      '0',
      'LTYPE',
      '2',
      'DASHDOT',
      '70',
      '64',
      '3',
      'Dash dot __ . __ . __ . __ . __ . __ . __ . __',
      '72',
      '65',
      '73',
      '4',
      '40',
      '15.0',
      '49',
      '10.0',
      '49',
      '-2.0',
      '49',
      '0.0',
      '49',
      '-2.0',
      '0',
      'LTYPE',
      '2',
      'PHANTOM',
      '70',
      '64',
      '3',
      'Phantom ______  __  __  ______  __  __  ______',
      '72',
      '65',
      '73',
      '6',
      '40',
      '40.0',
      '49',
      '20.0',
      '49',
      '-2.0',
      '49',
      '2.0',
      '49',
      '-2.0',
      '49',
      '2.0',
      '49',
      '-2.0',
      '0',
      'LTYPE',
      '2',
      'ISO-10W100',
      '70',
      '64',
      '3',
      '______  __  __  __  __  __  __  __',
      '72',
      '65',
      '73',
      '2',
      '40',
      '20.0',
      '49',
      '10.0',
      '49',
      '-2.0',
      '0',
      'ENDTAB',
      // LAYER table
      '0',
      'TABLE',
      '2',
      'LAYER',
      '70',
      '6',
      '0',
      'LAYER',
      '2',
      '0',
      '70',
      '0',
      '62',
      '7',
      '6',
      'CONTINUOUS',
      '0',
      'LAYER',
      '2',
      'WALLS',
      '70',
      '0',
      '62',
      '1',
      '6',
      'CONTINUOUS',
      '0',
      'LAYER',
      '2',
      'ROOMS',
      '70',
      '0',
      '62',
      '3',
      '6',
      'CONTINUOUS',
      '0',
      'LAYER',
      '2',
      'DOORS',
      '70',
      '0',
      '62',
      '4',
      '6',
      'CONTINUOUS',
      '0',
      'LAYER',
      '2',
      'WINDOWS',
      '70',
      '0',
      '62',
      '5',
      '6',
      'CONTINUOUS',
      '0',
      'LAYER',
      '2',
      'DIMENSIONS',
      '70',
      '0',
      '62',
      '6',
      '6',
      'CONTINUOUS',
      '0',
      'ENDTAB',
      // STYLE table
      '0',
      'TABLE',
      '2',
      'STYLE',
      '70',
      '1',
      '0',
      'STYLE',
      '2',
      'STANDARD',
      '70',
      '0',
      '40',
      '2.5',
      '41',
      '1.0',
      '50',
      '0.0',
      '42',
      '0.5',
      '3',
      'txt',
      '4',
      '',
      '0',
      'ENDTAB',
      // VIEW table
      '0',
      'TABLE',
      '2',
      'VIEW',
      '70',
      '0',
      '0',
      'ENDTAB',
      // UCS table
      '0',
      'TABLE',
      '2',
      'UCS',
      '70',
      '0',
      '0',
      'ENDTAB',
      // APPID table
      '0',
      'TABLE',
      '2',
      'APPID',
      '70',
      '1',
      '0',
      'APPID',
      '2',
      'ACAD',
      '70',
      '0',
      '0',
      'ENDTAB',
      // DIMSTYLE table
      '0',
      'TABLE',
      '2',
      'DIMSTYLE',
      '70',
      '1',
      '0',
      'DIMSTYLE',
      '2',
      'STANDARD',
      '70',
      '0',
      '3',
      'ISOCP',
      '40',
      '1.0',
      '0',
      'ENDTAB',
      // BLOCK_RECORD table
      '0',
      'TABLE',
      '2',
      'BLOCK_RECORD',
      '70',
      '0',
      '0',
      'BLOCK_RECORD',
      '2',
      '*MODEL_SPACE',
      '70',
      '0',
      '0',
      'BLOCK_RECORD',
      '2',
      '*PAPER_SPACE',
      '70',
      '0',
      '0',
      'ENDTAB',
      '0',
      'ENDSEC'
    ];

    return tables.join('\n');
  }

  /**
   * Generate DXF blocks section
   */
  generateBlocksSection(layout, options) {
    const blocks = [
      '0',
      'SECTION',
      '2',
      'BLOCKS',
      '0',
      'ENDSEC'
    ];

    return blocks.join('\n');
  }

  /**
   * Generate DXF entities section
   */
  generateEntitiesSection(layout, options) {
    const entities = ['0', 'SECTION', '2', 'ENTITIES'];

    // Plot boundary
    entities.push(
      '0',
      'LINE',
      '8',
      '0',
      '10',
      '0.0',
      '20',
      '0.0',
      '30',
      '0.0',
      '11',
      layout.plot.width.toFixed(this.precision),
      '21',
      '0.0',
      '31',
      '0.0'
    );

    entities.push(
      '0',
      'LINE',
      '8',
      '0',
      '10',
      layout.plot.width.toFixed(this.precision),
      '20',
      '0.0',
      '30',
      '0.0',
      '11',
      layout.plot.width.toFixed(this.precision),
      '21',
      layout.plot.length.toFixed(this.precision),
      '31',
      '0.0'
    );

    entities.push(
      '0',
      'LINE',
      '8',
      '0',
      '10',
      layout.plot.width.toFixed(this.precision),
      '20',
      layout.plot.length.toFixed(this.precision),
      '30',
      '0.0',
      '11',
      '0.0',
      '21',
      layout.plot.length.toFixed(this.precision),
      '31',
      '0.0'
    );

    entities.push(
      '0',
      'LINE',
      '8',
      '0',
      '10',
      '0.0',
      '20',
      layout.plot.length.toFixed(this.precision),
      '30',
      '0.0',
      '11',
      '0.0',
      '21',
      '0.0',
      '31',
      '0.0'
    );

    // Rooms
    layout.rooms.forEach(room => {
      const x1 = room.x.toFixed(this.precision);
      const y1 = room.y.toFixed(this.precision);
      const x2 = (room.x + room.width).toFixed(this.precision);
      const y2 = (room.y + room.height).toFixed(this.precision);

      // Room boundary
      entities.push(
        '0',
        'POLYLINE',
        '8',
        'ROOMS',
        '66',
        '1',
        '10',
        x1,
        '20',
        y1,
        '30',
        '0.0',
        '0',
        'VERTEX',
        '8',
        'ROOMS',
        '10',
        x2,
        '20',
        y1,
        '30',
        '0.0',
        '0',
        'VERTEX',
        '8',
        'ROOMS',
        '10',
        x2,
        '20',
        y2,
        '30',
        '0.0',
        '0',
        'VERTEX',
        '8',
        'ROOMS',
        '10',
        x1,
        '20',
        y2,
        '30',
        '0.0',
        '0',
        'VERTEX',
        '8',
        'ROOMS',
        '10',
        x1,
        '20',
        y1,
        '30',
        '0.0',
        '0',
        'SEQEND',
        '8',
        'ROOMS'
      );

      // Room label
      entities.push(
        '0',
        'TEXT',
        '8',
        'DIMENSIONS',
        '10',
        (room.x + room.width / 2).toFixed(this.precision),
        '20',
        (room.y + room.height / 2).toFixed(this.precision),
        '30',
        '0.0',
        '40',
        '2.5',
        '1',
        room.label,
        '50',
        '0.0'
      );

      // Room dimensions
      entities.push(
        '0',
        'LINE',
        '8',
        'DIMENSIONS',
        '10',
        x1,
        '20',
        (y1 - 1).toFixed(this.precision),
        '30',
        '0.0',
        '11',
        x2,
        '21',
        (y1 - 1).toFixed(this.precision),
        '31',
        '0.0'
      );

      entities.push(
        '0',
        'TEXT',
        '8',
        'DIMENSIONS',
        '10',
        ((parseFloat(x1) + parseFloat(x2)) / 2).toFixed(this.precision),
        '20',
        (y1 - 2).toFixed(this.precision),
        '30',
        '0.0',
        '40',
        '1.5',
        '1',
        `${room.width}'`,
        '50',
        '0.0'
      );
    });

    // Walls
    layout.walls.forEach(wall => {
      entities.push(
        '0',
        'LINE',
        '8',
        'WALLS',
        '10',
        wall.x1.toFixed(this.precision),
        '20',
        wall.y1.toFixed(this.precision),
        '30',
        '0.0',
        '11',
        wall.x2.toFixed(this.precision),
        '21',
        wall.y2.toFixed(this.precision),
        '31',
        '0.0'
      );
    });

    // Doors
    layout.doors.forEach(door => {
      entities.push(
        '0',
        'LINE',
        '8',
        'DOORS',
        '10',
        door.x.toFixed(this.precision),
        '20',
        door.y.toFixed(this.precision),
        '30',
        '0.0',
        '11',
        door.x.toFixed(this.precision),
        '21',
        (door.y + door.height).toFixed(this.precision),
        '31',
        '0.0'
      );
    });

    // Windows
    layout.windows.forEach(window => {
      entities.push(
        '0',
        'LINE',
        '8',
        'WINDOWS',
        '10',
        window.x.toFixed(this.precision),
        '20',
        window.y.toFixed(this.precision),
        '30',
        '0.0',
        '11',
        (window.x + window.width).toFixed(this.precision),
        '21',
        window.y.toFixed(this.precision),
        '31',
        '0.0'
      );
    });

    entities.push('0', 'ENDSEC');

    return entities.join('\n');
  }

  /**
   * Generate DXF objects section
   */
  generateObjectsSection(layout, options) {
    const objects = [
      '0',
      'SECTION',
      '2',
      'OBJECTS',
      '0',
      'DICTIONARY',
      '5',
      'C',
      '100',
      'AcDbDictionary',
      '281',
      '1',
      '3',
      'ACAD_GROUP',
      '350',
      'D',
      '3',
      'ACAD_LAYOUT',
      '350',
      '1A',
      '3',
      'ACAD_PLOTSETTINGS',
      '350',
      '1B',
      '3',
      'ACAD_PLOTSTYLENAME',
      '350',
      'E',
      '3',
      'ACAD_TABLESTYLE',
      '350',
      '16',
      '3',
      'ACAD_VISUALSTYLE',
      '350',
      'F',
      '3',
      'ACDBPLACEHOLDER',
      '350',
      '1C',
      '0',
      'ENDSEC',
      '0',
      'EOF'
    ];

    return objects.join('\n');
  }

  /**
   * Get layer information for the layout
   */
  getLayerInfo(layout) {
    return {
      '0': { count: 4, description: 'Plot boundary' },
      'WALLS': { count: layout.walls.length, description: 'Structural walls' },
      'ROOMS': { count: layout.rooms.length, description: 'Room boundaries' },
      'DOORS': { count: layout.doors.length, description: 'Door openings' },
      'WINDOWS': { count: layout.windows.length, description: 'Window openings' },
      'DIMENSIONS': { count: layout.rooms.length + 1, description: 'Room labels and dimensions' }
    };
  }
}

module.exports = new PreciseDxfExporter();